[window]
opacity = 0.8
title = "Alacritty"
dynamic_title = false
padding = { x = 10, y = 10 }

[cursor.style]
blinking = "Off"
shape = "Beam"
##vi_mode_style = "Underline"

[font]
size = 14

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Regular Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
]

[hints]
